package capture

// ProcessedMarkBit is reserved for packets generated by b4 (fake, replay,
// split/disorder, RST and QUIC packets). It is separate from the legacy queue
// mark and lets the kernel bypass contract evolve without changing unrelated
// routing marks.
const ProcessedMarkBit uint32 = 1 << 27

const ProcessedMarkMask uint32 = ProcessedMarkBit

func ProcessedMarkFor(legacyMark uint) uint32 {
	return uint32(legacyMark) | ProcessedMarkBit
}

func MatchesMark(mark, value, mask uint32) bool {
	return mask != 0 && mark&mask == value&mask
}

// IsProcessedMark accepts the new reserved bit and the current B4 queue mark
// during migration. The legacy comparison is deliberately exact: arbitrary
// routing marks must not be treated as generated packets.
func IsProcessedMark(mark uint32, legacyMark uint) bool {
	return mark&ProcessedMarkMask == ProcessedMarkBit || mark == uint32(legacyMark)
}
