// Code generated by tools/gen_capability_deps_go.py from
// specs/registries/capability_dependencies.yaml. DO NOT EDIT.
//
// Canonical Capability Dependency Graph (FB-36, b4x-0yf). Single source of
// truth: specs/registries/capability_dependencies.yaml. Encodes the
// normative execution schedule (B4X_AUDIT_FIX_TASKS v2 §FB-36): parallel
// physical execution where safe, strict dependency aggregation (missing
// upstream dependency blocks downstream PASS).
package validation


// CapabilityDeclaredTotal is the declared registry total
// (generator enforces declared_total == computed_total == count(capabilities)).
const CapabilityDeclaredTotal = 10

// CapabilityDependency is one canonical capability stage of the
// FB-36 execution scheduling graph.
type CapabilityDependency struct {
	ID       string   // canonical capability id
	Name     string   // normative stage name
	Layer    int      // monotone graph depth; parallel wave grouping
	Requires []string // upstream capabilities (dependencies first)
	Parallel bool     // may run in parallel (not in the strict chain)
	Optional bool     // activated only when selected (base WARP readiness)
}

// capabilityDependencies holds the full canonical capability list (auto-generated).
var capabilityDependencies = []CapabilityDependency{
	{
		ID:       "classifier", 
		Name:     "Classifier/Capture", 
		Layer:    0, 
		Requires: nil, 
		Parallel: true, 
		Optional: false, 
	},
	{
		ID:       "tgb", 
		Name:     "Telegram bridge (parallel after capture/routing prerequisites)", 
		Layer:    1, 
		Requires: []string{"classifier"}, 
		Parallel: true, 
		Optional: false, 
	},
	{
		ID:       "visibility", 
		Name:     "CSI + GSO/RST + PPE visibility", 
		Layer:    1, 
		Requires: []string{"classifier"}, 
		Parallel: false, 
		Optional: false, 
	},
	{
		ID:       "progress", 
		Name:     "Progress/SPF", 
		Layer:    2, 
		Requires: []string{"visibility"}, 
		Parallel: false, 
		Optional: false, 
	},
	{
		ID:       "mon", 
		Name:     "MON (continuous blocking monitoring)", 
		Layer:    3, 
		Requires: []string{"progress"}, 
		Parallel: false, 
		Optional: false, 
	},
	{
		ID:       "abd", 
		Name:     "ABD (authoritative blocking diagnosis)", 
		Layer:    4, 
		Requires: []string{"mon"}, 
		Parallel: false, 
		Optional: false, 
	},
	{
		ID:       "ddi", 
		Name:     "DDI/Discovery", 
		Layer:    5, 
		Requires: []string{"abd"}, 
		Parallel: false, 
		Optional: false, 
	},
	{
		ID:       "canary", 
		Name:     "Scoped canary / runtimecontrol", 
		Layer:    6, 
		Requires: []string{"ddi"}, 
		Parallel: false, 
		Optional: false, 
	},
	{
		ID:       "warp", 
		Name:     "Base WARP causal readiness", 
		Layer:    7, 
		Requires: []string{"mon", "abd", "ddi", "canary"}, 
		Parallel: false, 
		Optional: true, 
	},
	{
		ID:       "service_profile", 
		Name:     "Service Profile recommendation readiness", 
		Layer:    8, 
		Requires: []string{"warp", "abd", "ddi"}, 
		Parallel: false, 
		Optional: false, 
	},
}

// Capabilities returns the full canonical capability dependency registry.
func Capabilities() []CapabilityDependency { return capabilityDependencies }

// CapabilityByID returns the capability with the given canonical id.
func CapabilityByID(id string) (CapabilityDependency, bool) {
	for _, c := range capabilityDependencies {
		if c.ID == id {
			return c, true
		}
	}
	return CapabilityDependency{}, false
}

