// Code generated by tools/gen_causal_matrix_go.py from
// specs/registries/causal_eligibility_matrix.yaml. DO NOT EDIT.
//
// Causal eligibility matrix (FB-31, b4x-cka). Single source of truth:
// specs/registries/causal_eligibility_matrix.yaml. Maps every failure
// family to eligible/forbidden candidate families, mandatory narrower
// families, prerequisites, controls, target validation and scoped transport
// authorization rules.
package validation


// CandidateFamilyKind is the catalog role of a candidate family.
type CandidateFamilyKind string

const (
	CandidateKindEligible  CandidateFamilyKind = "eligible"
	CandidateKindShadow    CandidateFamilyKind = "shadow"
	CandidateKindForbidden CandidateFamilyKind = "forbidden"
)

// CandidateFamily is one candidate family in the FB-31 catalog.
type CandidateFamily struct {
	Family    string
	Kind      CandidateFamilyKind
	Transport bool
	Note      string
}

// candidateFamilies holds the candidate family catalog (auto-generated).
var candidateFamilies = []CandidateFamily{
	{
		Family:    "direct", 
		Kind:      CandidateFamilyKind("eligible"), 
		Transport: false, 
		Note:      "baseline direct path", 
	},
	{
		Family:    "trusted_doh", 
		Kind:      CandidateFamilyKind("eligible"), 
		Transport: false, 
		Note:      "trusted DoH resolver candidates", 
	},
	{
		Family:    "system_forward", 
		Kind:      CandidateFamilyKind("eligible"), 
		Transport: false, 
		Note:      "system resolver forward candidates", 
	},
	{
		Family:    "bootstrap_ip_resolver", 
		Kind:      CandidateFamilyKind("eligible"), 
		Transport: false, 
		Note:      "bootstrap-IP resolver candidates", 
	},
	{
		Family:    "cname_aware_resolution", 
		Kind:      CandidateFamilyKind("eligible"), 
		Transport: false, 
		Note:      "CNAME-aware target resolution", 
	},
	{
		Family:    "resolver_only", 
		Kind:      CandidateFamilyKind("shadow"), 
		Transport: false, 
		Note:      "resolver-only shadow comparison (probe-only)", 
	},
	{
		Family:    "marker_split_near_sni", 
		Kind:      CandidateFamilyKind("eligible"), 
		Transport: false, 
		Note:      "marker split near SNI/extensions", 
	},
	{
		Family:    "canonical_clienthello_profile", 
		Kind:      CandidateFamilyKind("eligible"), 
		Transport: false, 
		Note:      "real/canonical ClientHello profiles", 
	},
	{
		Family:    "bounded_tls_profile_variant", 
		Kind:      CandidateFamilyKind("eligible"), 
		Transport: false, 
		Note:      "bounded TLS profile variants", 
	},
	{
		Family:    "generic_fake_injection", 
		Kind:      CandidateFamilyKind("forbidden"), 
		Transport: false, 
		Note:      "generic fake injection never authorized (v1.2 13.4)", 
	},
	{
		Family:    "bounded_disorder_desync", 
		Kind:      CandidateFamilyKind("eligible"), 
		Transport: false, 
		Note:      "bounded disorder/desync after active reset", 
	},
	{
		Family:    "low_amplification_fake", 
		Kind:      CandidateFamilyKind("eligible"), 
		Transport: false, 
		Note:      "low-amplification fake strategies", 
	},
	{
		Family:    "split_around_markers", 
		Kind:      CandidateFamilyKind("eligible"), 
		Transport: false, 
		Note:      "split around authoritative markers", 
	},
	{
		Family:    "spf_scoped_recovery", 
		Kind:      CandidateFamilyKind("eligible"), 
		Transport: false, 
		Note:      "silent-path scoped recovery (suppression gates required)", 
	},
	{
		Family:    "minimal_packet_candidates", 
		Kind:      CandidateFamilyKind("eligible"), 
		Transport: false, 
		Note:      "minimal-packet candidates (L4 budget)", 
	},
	{
		Family:    "low_complexity_direct", 
		Kind:      CandidateFamilyKind("eligible"), 
		Transport: false, 
		Note:      "low-complexity direct strategy", 
	},
	{
		Family:    "high_amplification_variants", 
		Kind:      CandidateFamilyKind("forbidden"), 
		Transport: false, 
		Note:      "high packet amplification never selected", 
	},
	{
		Family:    "bounded_split_shaping", 
		Kind:      CandidateFamilyKind("eligible"), 
		Transport: false, 
		Note:      "bounded split/shaping ranges around observed interval", 
	},
	{
		Family:    "safe_quic_block_fallback", 
		Kind:      CandidateFamilyKind("eligible"), 
		Transport: false, 
		Note:      "safe QUIC block/fallback", 
	},
	{
		Family:    "tcp_candidate_matrix", 
		Kind:      CandidateFamilyKind("eligible"), 
		Transport: false, 
		Note:      "TCP candidate matrix", 
	},
	{
		Family:    "direct_quic", 
		Kind:      CandidateFamilyKind("eligible"), 
		Transport: false, 
		Note:      "direct QUIC preserved when target-specific QUIC controls pass", 
	},
	{
		Family:    "scoped_transport", 
		Kind:      CandidateFamilyKind("eligible"), 
		Transport: true, 
		Note:      "WARP/SOCKS/TUN - only scoped eligible-to-test with authoritative evidence", 
	},
	{
		Family:    "ip_family_switch", 
		Kind:      CandidateFamilyKind("eligible"), 
		Transport: false, 
		Note:      "alternative address-family experiment", 
	},
	{
		Family:    "target_ip_variants", 
		Kind:      CandidateFamilyKind("eligible"), 
		Transport: false, 
		Note:      "alternative target IP candidates", 
	},
	{
		Family:    "revalidation_probe", 
		Kind:      CandidateFamilyKind("shadow"), 
		Transport: false, 
		Note:      "revalidation on actual target/component (probe-only)", 
	},
	{
		Family:    "white_sni_promotion", 
		Kind:      CandidateFamilyKind("forbidden"), 
		Transport: false, 
		Note:      "white SNI has no production eligibility (v1.2 21.9)", 
	},
}

// CausalEligibility is the FB-31 mapping of one failure family.
type CausalEligibility struct {
	Family                  string
	Title                   string
	SourceDoc               string
	SourceSection           string
	Hypotheses              []string
	EligibleCandidateFamilies  []string
	ForbiddenCandidateFamilies []string
	MandatoryNarrowerFamilies  []string
	ShadowCandidateFamilies    []string
	Prerequisites           []string
	Controls                []string
	TargetValidation        []string
	TransportAuthorization  string
	RequiredEvidenceAuthority string
}

// CausalEligibilityDeclaredTotal is the declared registry total
// (generator enforces declared_total == computed_total == count(valid entries)).
const CausalEligibilityDeclaredTotal = 9

// causalEligibilities holds the full failure family matrix (auto-generated).
var causalEligibilities = []CausalEligibility{
	{
		Family:                  "dns_interception", 
		Title:                   "DNS interception", 
		SourceDoc:               "B4X_POST_V23_ADAPTIVE_BLOCKING_DETECTOR_AND_GUIDED_STRATEGY_SEARCH_ADDENDUM_v1.2.md", 
		SourceSection:           "21.1", 
		Hypotheses:              nil, 
		EligibleCandidateFamilies:  []string{"trusted_doh", "system_forward", "bootstrap_ip_resolver", "cname_aware_resolution"}, 
		ForbiddenCandidateFamilies: []string{"scoped_transport", "direct_quic"}, 
		MandatoryNarrowerFamilies:  nil, 
		ShadowCandidateFamilies:    []string{"resolver_only"}, 
		Prerequisites:           []string{"resolution_snapshot_fresh", "config_generation_current"}, 
		Controls:                []string{"same_client_controls_healthy"}, 
		TargetValidation:        []string{"target_specific_resolution_probe"}, 
		TransportAuthorization:  "none", 
		RequiredEvidenceAuthority: "", 
	},
	{
		Family:                  "tls_fingerprint_specific", 
		Title:                   "TLS 1.3 or fingerprint-specific failure", 
		SourceDoc:               "B4X_POST_V23_ADAPTIVE_BLOCKING_DETECTOR_AND_GUIDED_STRATEGY_SEARCH_ADDENDUM_v1.2.md", 
		SourceSection:           "21.2", 
		Hypotheses:              nil, 
		EligibleCandidateFamilies:  []string{"marker_split_near_sni", "canonical_clienthello_profile", "bounded_tls_profile_variant"}, 
		ForbiddenCandidateFamilies: []string{"generic_fake_injection", "scoped_transport"}, 
		MandatoryNarrowerFamilies:  []string{"canonical_clienthello_profile"}, 
		ShadowCandidateFamilies:    nil, 
		Prerequisites:           []string{"fingerprint_exact_observed"}, 
		Controls:                []string{"same_client_controls_healthy"}, 
		TargetValidation:        []string{"target_specific_fingerprint_repro"}, 
		TransportAuthorization:  "none", 
		RequiredEvidenceAuthority: "", 
	},
	{
		Family:                  "active_reset_after_client_hello", 
		Title:                   "Active reset after ClientHello", 
		SourceDoc:               "B4X_POST_V23_ADAPTIVE_BLOCKING_DETECTOR_AND_GUIDED_STRATEGY_SEARCH_ADDENDUM_v1.2.md", 
		SourceSection:           "21.3", 
		Hypotheses:              nil, 
		EligibleCandidateFamilies:  []string{"bounded_disorder_desync", "low_amplification_fake", "split_around_markers"}, 
		ForbiddenCandidateFamilies: []string{"scoped_transport"}, 
		MandatoryNarrowerFamilies:  nil, 
		ShadowCandidateFamilies:    nil, 
		Prerequisites:           []string{"rst_direction_sequence_observed"}, 
		Controls:                []string{"rst_direction_plausibility", "shadow_comparison"}, 
		TargetValidation:        []string{"target_specific_reset_repro"}, 
		TransportAuthorization:  "none", 
		RequiredEvidenceAuthority: "", 
	},
	{
		Family:                  "silent_drop_stall", 
		Title:                   "Silent drop or stall", 
		SourceDoc:               "B4X_POST_V23_ADAPTIVE_BLOCKING_DETECTOR_AND_GUIDED_STRATEGY_SEARCH_ADDENDUM_v1.2.md", 
		SourceSection:           "21.4", 
		Hypotheses:              nil, 
		EligibleCandidateFamilies:  []string{"spf_scoped_recovery"}, 
		ForbiddenCandidateFamilies: []string{"scoped_transport"}, 
		MandatoryNarrowerFamilies:  nil, 
		ShadowCandidateFamilies:    nil, 
		Prerequisites:           []string{"suppression_gates_passed"}, 
		Controls:                []string{"suppression_gates", "fresh_control"}, 
		TargetValidation:        []string{"target_body_progress_proof"}, 
		TransportAuthorization:  "none", 
		RequiredEvidenceAuthority: "", 
	},
	{
		Family:                  "l4_packet_budget", 
		Title:                   "L4 packet budget violations", 
		SourceDoc:               "B4X_POST_V23_ADAPTIVE_BLOCKING_DETECTOR_AND_GUIDED_STRATEGY_SEARCH_ADDENDUM_v1.2.md", 
		SourceSection:           "21.5", 
		Hypotheses:              nil, 
		EligibleCandidateFamilies:  []string{"minimal_packet_candidates", "low_complexity_direct"}, 
		ForbiddenCandidateFamilies: []string{"high_amplification_variants", "scoped_transport"}, 
		MandatoryNarrowerFamilies:  []string{"minimal_packet_candidates"}, 
		ShadowCandidateFamilies:    nil, 
		Prerequisites:           []string{"amplification_measured"}, 
		Controls:                []string{"packet_budget_bounded"}, 
		TargetValidation:        []string{"target_specific_amplification_repro"}, 
		TransportAuthorization:  "none", 
		RequiredEvidenceAuthority: "", 
	},
	{
		Family:                  "byte_window_transfer", 
		Title:                   "Byte-window transfer failure", 
		SourceDoc:               "B4X_POST_V23_ADAPTIVE_BLOCKING_DETECTOR_AND_GUIDED_STRATEGY_SEARCH_ADDENDUM_v1.2.md", 
		SourceSection:           "21.6", 
		Hypotheses:              []string{"byte_window_transfer_interference"}, 
		EligibleCandidateFamilies:  []string{"bounded_split_shaping"}, 
		ForbiddenCandidateFamilies: []string{"scoped_transport"}, 
		MandatoryNarrowerFamilies:  nil, 
		ShadowCandidateFamilies:    nil, 
		Prerequisites:           []string{"interval_observed"}, 
		Controls:                []string{"target_body_progress_proof", "fresh_control"}, 
		TargetValidation:        []string{"target_body_progress_proof"}, 
		TransportAuthorization:  "none", 
		RequiredEvidenceAuthority: "", 
	},
	{
		Family:                  "quic_only", 
		Title:                   "QUIC-only failure", 
		SourceDoc:               "B4X_POST_V23_ADAPTIVE_BLOCKING_DETECTOR_AND_GUIDED_STRATEGY_SEARCH_ADDENDUM_v1.2.md", 
		SourceSection:           "21.7", 
		Hypotheses:              nil, 
		EligibleCandidateFamilies:  []string{"safe_quic_block_fallback", "tcp_candidate_matrix", "direct_quic"}, 
		ForbiddenCandidateFamilies: []string{"scoped_transport"}, 
		MandatoryNarrowerFamilies:  []string{"tcp_candidate_matrix"}, 
		ShadowCandidateFamilies:    nil, 
		Prerequisites:           []string{"tcp_path_healthy"}, 
		Controls:                []string{"target_specific_quic_controls"}, 
		TargetValidation:        []string{"target_specific_quic_repro"}, 
		TransportAuthorization:  "none", 
		RequiredEvidenceAuthority: "", 
	},
	{
		Family:                  "ip_cidr_route_block", 
		Title:                   "IP/CIDR route block suspicion", 
		SourceDoc:               "B4X_POST_V23_ADAPTIVE_BLOCKING_DETECTOR_AND_GUIDED_STRATEGY_SEARCH_ADDENDUM_v1.2.md", 
		SourceSection:           "21.8", 
		Hypotheses:              []string{"path_local_syn_filter_suspected", "path_local_syn_filter_probable", "path_local_syn_filter_confirmed", "service_ip_filter_probable", "service_cidr_filter_probable", "shared_transport_path_block_probable", "multi_origin_direct_connect_failure_with_reference_success"}, 
		EligibleCandidateFamilies:  []string{"scoped_transport", "ip_family_switch", "target_ip_variants", "low_complexity_direct"}, 
		ForbiddenCandidateFamilies: []string{"high_amplification_variants"}, 
		MandatoryNarrowerFamilies:  nil, 
		ShadowCandidateFamilies:    nil, 
		Prerequisites:           []string{"multiple_target_ips_confirmed", "controls_healthy"}, 
		Controls:                []string{"route_block_controls", "same_client_controls_healthy"}, 
		TargetValidation:        []string{"target_specific_transport_probe"}, 
		TransportAuthorization:  "scoped-eligible-to-test", 
		RequiredEvidenceAuthority: "authoritative-abd", 
	},
	{
		Family:                  "white_sni_evidence", 
		Title:                   "White SNI evidence", 
		SourceDoc:               "B4X_POST_V23_ADAPTIVE_BLOCKING_DETECTOR_AND_GUIDED_STRATEGY_SEARCH_ADDENDUM_v1.2.md", 
		SourceSection:           "21.9", 
		Hypotheses:              nil, 
		EligibleCandidateFamilies:  nil, 
		ForbiddenCandidateFamilies: []string{"white_sni_promotion", "scoped_transport"}, 
		MandatoryNarrowerFamilies:  nil, 
		ShadowCandidateFamilies:    []string{"revalidation_probe"}, 
		Prerequisites:           []string{"source_target_asn_recorded"}, 
		Controls:                nil, 
		TargetValidation:        []string{"actual_target_revalidation"}, 
		TransportAuthorization:  "none", 
		RequiredEvidenceAuthority: "", 
	},
}

// CandidateFamilies returns the candidate family catalog.
func CandidateFamilies() []CandidateFamily { return candidateFamilies }

// CausalEligibilities returns the full failure family matrix.
func CausalEligibilities() []CausalEligibility { return causalEligibilities }

// CausalEligibilityByFamily returns the mapping for one failure family.
func CausalEligibilityByFamily(family string) (CausalEligibility, bool) {
	for _, e := range causalEligibilities {
		if e.Family == family {
			return e, true
		}
	}
	return CausalEligibility{}, false
}

