package observability

// ABD hard-gate counters (FB-02 ABD section, §39-§42 of
// B4X_POST_V23_ADAPTIVE_BLOCKING_DETECTOR_AND_GUIDED_STRATEGY_SEARCH_ADDENDUM_v1.2).
// Metric names match the canonical registry gate IDs exactly. Each counter is
// incremented only on the violating branch of the production ABD lifecycle
// guards in src/detector/hard_gate_producers.go (detector safety, DNS/TLS/QUIC
// classification, L4 thresholds, blocking-profile/DDI chain, monitoring
// adapter). All seventy-nine are zero-tolerance violation counters: the
// window delta must stay 0 for the production promotion verdict. Six
// additional ABD counters (resolution-erasure / multi-vantage, FB-29/FB-30)
// live in detector producers declared earlier.
const (
	MetricABDSingleProbeConfirmed                         = "detector_single_probe_confirmed_total"
	MetricABDExceptionStringOnlyConfirmed                 = "detector_exception_string_only_confirmed_total"
	MetricABDStaticTargetOnlyHighConfidence               = "detector_static_target_only_high_confidence_total"
	MetricABDSelfInterference                             = "detector_self_interference_total"
	MetricABDNativePathUnproven                           = "detector_native_path_unproven_total"
	MetricABDCaptureInvalidPacketVerdict                  = "detector_capture_invalid_packet_verdict_total"
	MetricABDControlFailureIgnored                        = "detector_control_failure_ignored_total"
	MetricABDDupEvidenceConfidenceIncrease                = "detector_duplicate_evidence_confidence_increase_total"
	MetricABDCrossComponentEvidenceMerge                  = "detector_cross_component_evidence_merge_total"
	MetricABDCrossGenerationEvidenceMerge                 = "detector_cross_generation_evidence_merge_total"
	MetricABDUnboundedDynamicScan                         = "detector_unbounded_dynamic_scan_total"
	MetricABDResourceBudgetBypass                         = "detector_resource_budget_bypass_total"
	MetricABDSensitiveExport                              = "detector_sensitive_export_total"
	MetricABDHostDeadSingleReferenceFailure               = "detector_host_dead_from_single_reference_failure_total"
	MetricABDReferencePathUnhealthyUsed                   = "detector_reference_path_unhealthy_used_total"
	MetricABDReferencePathAsActionAuth                    = "detector_reference_path_used_as_action_authorization_total"
	MetricABDPartialRunProfileCompiled                    = "detector_partial_run_profile_compiled_total"
	MetricABDResumeCrossNetworkContext                    = "detector_resume_cross_network_context_total"
	MetricABDCapacitySelfInterference                     = "detector_capacity_self_interference_total"
	MetricABDDNSSingleResolverSpoof                       = "detector_dns_single_resolver_spoof_confirmed_total"
	MetricABDDNSCdnVarianceMisclassified                  = "detector_dns_cdn_variance_misclassified_total"
	MetricABDUnverifiedMITMVerdict                        = "detector_unverified_mitm_verdict_total"
	MetricABDTLSAvailabilityIntegrityConflate             = "detector_tls_availability_integrity_conflation_total"
	MetricABDTLSFingerprintUnlabeled                      = "detector_tls_fingerprint_unlabeled_total"
	MetricABDQUICSingleTargetGlobalUDP                    = "detector_quic_single_target_global_udp_verdict_total"
	MetricABDQUICTCPEvidenceConflation                    = "detector_quic_tcp_evidence_conflation_total"
	MetricABDValidAppErrorDPI                             = "detector_valid_application_error_dpi_total"
	MetricABDHeadOnlyAvailableVerdict                     = "detector_head_only_available_verdict_total"
	MetricABDPartialProgressDiscarded                     = "detector_partial_progress_discarded_total"
	MetricABDSmallObjectClassifiedThrottled               = "detector_small_object_classified_throttled_total"
	MetricABDFixed16kbWindowNoProfile                     = "detector_fixed_16kb_window_confirmed_without_profile_total"
	MetricABDPacketThresholdAsByte                        = "detector_packet_threshold_reported_as_byte_threshold_total"
	MetricABDByteThresholdAsPacket                        = "detector_byte_threshold_reported_as_packet_threshold_total"
	MetricABDGsoSkbCountAsWirePacket                      = "detector_gso_skb_count_as_wire_packet_total"
	MetricABDSingleOriginL4BudgetConfirmed                = "detector_single_origin_l4_budget_confirmed_total"
	MetricABDServerHeaderLimitDPI                         = "detector_server_header_limit_dpi_total"
	MetricABDRetransmissionAsProgress                     = "detector_retransmission_counted_as_progress_total"
	MetricABDL4ThresholdWithoutControls                   = "detector_l4_threshold_without_controls_total"
	MetricABDBlockingProfileWithoutTargetPlan             = "blocking_profile_without_target_plan_total"
	MetricABDBlockingProfileWithoutNetCtx                 = "blocking_profile_without_network_context_total"
	MetricABDBlockingProfileWithoutProvenance             = "blocking_profile_without_provenance_total"
	MetricABDBlockingProfileMutatedAfterCompile           = "blocking_profile_mutated_after_compile_total"
	MetricABDBlockingProfileHighConfidenceContradiction   = "blocking_profile_high_confidence_with_contradiction_total"
	MetricABDBlockingProfileDirectActionAuth              = "blocking_profile_direct_action_authorization_total"
	MetricABDBlockingProfileDirectProdWrite               = "blocking_profile_direct_production_write_total"
	MetricABDGuidedSearchSkippedBaseline                  = "guided_search_skipped_baseline_total"
	MetricABDGuidedSearchDisabledFullFallback             = "guided_search_disabled_full_fallback_total"
	MetricABDGuidedSearchOverrodeBaseline                 = "guided_search_profile_overrode_current_baseline_total"
	MetricABDGuidedSearchUnvalidatedPromotion             = "guided_search_target_unvalidated_promotion_total"
	MetricABDGuidedSearchCrossServiceAction               = "guided_search_cross_service_action_total"
	MetricABDGuidedSearchWhiteSNIDirectPromotion          = "guided_search_white_sni_direct_promotion_total"
	MetricABDGuidedSearchFalseSavingsReport               = "guided_search_false_savings_report_total"
	MetricABDGuidedSearchRequiredComponentUncovered       = "guided_search_required_component_uncovered_total"
	MetricABDGuidedSearchCoverageIgnoredControlRegression = "guided_search_coverage_ignored_control_regression_total"
	MetricABDGuidedSearchCrossServiceSetCover             = "guided_search_cross_service_set_cover_total"
	MetricABDGuidedSearchExcludedTargetHidden             = "guided_search_excluded_target_hidden_total"
	MetricABDGuidedSearchMoreComplexPreferredNoGain       = "guided_search_more_complex_candidate_preferred_without_gain_total"
	MetricABDGuidedSearchUnverifiedShortlist              = "guided_search_unverified_shortlist_promotion_total"
	MetricABDMonitorRequestDirectAction                   = "detector_monitor_request_direct_action_total"
	MetricABDMonitorRequestWithoutTargetPlan              = "detector_monitor_request_without_target_plan_overlay_total"
	MetricABDMonitorRequestWithoutNetworkCtx              = "detector_monitor_request_without_network_context_total"
	MetricABDMonitorRequestWithoutConfigGen               = "detector_monitor_request_without_config_generation_total"
	MetricABDMonitorRequestWithoutBudgetToken             = "detector_monitor_request_without_budget_token_total"
	MetricABDMonitorRequestExpiredAccepted                = "detector_monitor_request_expired_accepted_total"
	MetricABDProvisionalMonitorProfileCompiled            = "detector_provisional_monitor_evidence_profile_compiled_total"
	MetricABDPassiveObservationAsIndependentProbe         = "detector_passive_observation_counted_as_independent_probe_total"
	MetricABDMonitorRecurrenceAsIndependence              = "detector_monitor_recurrence_counted_as_evidence_independence_total"
	MetricABDClientResolutionReplacedSilently             = "detector_client_resolution_replaced_silently_total"
	MetricABDProbeWithoutResolutionBinding                = "detector_probe_without_resolution_binding_total"
	MetricABDCnameTerminalIPMisattributed                 = "detector_cname_terminal_ip_misattributed_total"
	MetricABDMultiIPPartialFailureHidden                  = "detector_multi_ip_partial_failure_hidden_total"
	MetricABDStaleClientResolutionUsed                    = "detector_stale_client_resolution_used_total"
	MetricABDResultWithoutAssessmentLink                  = "detector_result_without_monitor_assessment_link_total"
	MetricABDResultCrossNetworkContext                    = "detector_result_cross_network_context_total"
	MetricABDResultCrossConfigGeneration                  = "detector_result_cross_config_generation_total"
	MetricABDResultCrossMonitoringEpoch                   = "detector_result_cross_monitoring_epoch_total"
	MetricABDIncompleteRunFinalProfile                    = "detector_incomplete_run_final_profile_total"
	MetricABDMonitorResultActionAuthorization             = "detector_monitor_result_action_authorization_total"
	MetricABDMonitorResultDeliveryIdentityMismatch        = "detector_monitor_result_delivery_identity_mismatch_total"
)
