package managed

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"sort"
	"strings"
)

const managedStaticServerName = "b4x-upstream"

// InstanceSpec is the deterministic causal identity of one managed instance
// (addendum §44): one upstream resolver, optional one relay, one protocol
// family, one IP family preference, one generated config digest, one
// loopback listener, one B4X DNSPathID.
type InstanceSpec struct {
	Family          string // dnscrypt | pqdnscrypt | anonymized-dnscrypt | odoh | doh | doh3
	ServerName      string // explicit reviewed server name from signed catalog
	ServerStamp     string // signed DNS stamp; production runtime requires this
	RelayName       string // required for anonymized-dnscrypt and odoh
	ListenAddr      string // loopback only, e.g. 127.0.0.1:55331
	IPv4            bool
	IPv6            bool
	ForceTCP        bool
	HTTP3           bool // only for doh3 candidate
	Cache           bool
	CacheSize       int
	Diagnostic      bool // diagnostic instance: cache off, ephemeral
	RequireNoLog    bool
	RequireNoFilter bool
	RequireDNSSEC   bool
}

// allowedKeys is the pinned config key allowlist. The generator rejects
// unknown/deprecated keys (addendum Appendix D: "Config generator must
// reject unknown/deprecated keys").
var allowedKeys = map[string]bool{
	"listen_addresses": true, "server_names": true,
	"ipv4_servers": true, "ipv6_servers": true,
	"dnscrypt_servers": true, "doh_servers": true, "odoh_servers": true,
	"force_tcp": true, "http3": true,
	"require_nolog": true, "require_nofilter": true, "require_dnssec": true,
	"lb_strategy": true, "lb_estimator": true,
	"cache": true, "cache_size": true, "cache_neg_ttl": true,
	"cert_refresh_concurrency": true, "ignore_system_dns": true,
	"stamp": true,
	"query_log.file": false, "edns_client_subnet": false, // privacy defaults: intentionally unset
}

// ValidateSpec enforces the generated-config requirements (§46). ServerStamp
// remains optional for legacy unit fixtures, but production ManagedProvider
// capability checks require it before the instance can become AVAILABLE.
func ValidateSpec(s InstanceSpec) error {
	if s.ServerName == "" {
		return fmt.Errorf("managed instance requires one explicit server name")
	}
	if s.ServerStamp != "" && !strings.HasPrefix(s.ServerStamp, "sdns://") {
		return fmt.Errorf("managed instance server stamp must be sdns://")
	}
	if s.ListenAddr == "" || !strings.HasPrefix(s.ListenAddr, "127.0.0.1:") {
		return fmt.Errorf("managed listener must be loopback-owned, got %q", s.ListenAddr)
	}
	switch s.Family {
	case "dnscrypt", "pqdnscrypt", "doh":
		if s.RelayName != "" {
			return fmt.Errorf("family %s must not bind a relay", s.Family)
		}
	case "anonymized-dnscrypt", "odoh":
		if s.RelayName == "" {
			return fmt.Errorf("family %s requires one explicit relay", s.Family)
		}
	case "doh3":
		if !s.HTTP3 {
			return fmt.Errorf("doh3 candidate requires http3 enabled")
		}
	default:
		return fmt.Errorf("unknown managed family %q", s.Family)
	}
	if s.HTTP3 && s.Family != "doh3" {
		return fmt.Errorf("http3 allowed only for doh3 candidate")
	}
	return nil
}

// GenerateConfig renders the TOML config for one causal instance. Hidden
// multi-server random selection is impossible: lb_strategy is pinned to
// 'first' with the estimator off and exactly one server name (§44/§46).
// When ServerStamp is present, a static resolver entry makes the generated
// config independent from external/default resolver source lists.
func GenerateConfig(s InstanceSpec) (string, error) {
	if err := ValidateSpec(s); err != nil {
		return "", err
	}
	var b strings.Builder
	b.WriteString("# Generated by B4X for one causal path instance\n")
	fmt.Fprintf(&b, "listen_addresses = ['%s']\n", s.ListenAddr)
	serverName := s.ServerName
	if s.ServerStamp != "" {
		serverName = managedStaticServerName
	}
	fmt.Fprintf(&b, "server_names = ['%s']\n", serverName)
	fmt.Fprintf(&b, "ipv4_servers = %v\n", s.IPv4)
	fmt.Fprintf(&b, "ipv6_servers = %v\n", s.IPv6)
	fmt.Fprintf(&b, "dnscrypt_servers = %v\n", s.Family == "dnscrypt" || s.Family == "pqdnscrypt" || s.Family == "anonymized-dnscrypt")
	fmt.Fprintf(&b, "doh_servers = %v\n", s.Family == "doh" || s.Family == "doh3")
	fmt.Fprintf(&b, "odoh_servers = %v\n", s.Family == "odoh")
	fmt.Fprintf(&b, "force_tcp = %v\n", s.ForceTCP)
	fmt.Fprintf(&b, "http3 = %v\n", s.HTTP3)
	fmt.Fprintf(&b, "require_nolog = %v\n", s.RequireNoLog)
	fmt.Fprintf(&b, "require_nofilter = %v\n", s.RequireNoFilter)
	fmt.Fprintf(&b, "require_dnssec = %v\n", s.RequireDNSSEC)
	b.WriteString("# B4X owns causal selection; no hidden pool\n")
	b.WriteString("lb_strategy = 'first'\n")
	b.WriteString("lb_estimator = false\n")
	cache := s.Cache && !s.Diagnostic
	fmt.Fprintf(&b, "cache = %v\n", cache)
	size := s.CacheSize
	if size <= 0 {
		size = 1024
	}
	fmt.Fprintf(&b, "cache_size = %d\n", size)
	b.WriteString("# Privacy defaults: query_log.file and edns_client_subnet intentionally unset\n")
	b.WriteString("cert_refresh_concurrency = 1\n")
	b.WriteString("ignore_system_dns = true\n")
	if s.ServerStamp != "" {
		b.WriteString("\n[static.'" + managedStaticServerName + "']\n")
		fmt.Fprintf(&b, "stamp = '%s'\n", s.ServerStamp)
	}
	return b.String(), nil
}

// ConfigDigest is the deterministic digest of the generated config.
func ConfigDigest(cfg string) string {
	sum := sha256.Sum256([]byte(cfg))
	return hex.EncodeToString(sum[:16])
}

// ValidateKeys rejects configs containing keys outside the pinned allowlist
// or privacy-prohibited keys. Only the exact B4X-owned static resolver table
// is permitted; arbitrary TOML sections remain forbidden.
func ValidateKeys(cfg string) error {
	inStatic := false
	for _, line := range strings.Split(cfg, "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		if strings.HasPrefix(line, "[") {
			if line != "[static.'"+managedStaticServerName+"']" {
				return fmt.Errorf("unknown config section %q", line)
			}
			inStatic = true
			continue
		}
		key := strings.TrimSpace(strings.SplitN(line, "=", 2)[0])
		allowed, known := allowedKeys[key]
		if !known {
			return fmt.Errorf("unknown config key %q", key)
		}
		if !allowed {
			return fmt.Errorf("prohibited config key %q", key)
		}
		if key == "stamp" && !inStatic {
			return fmt.Errorf("stamp is only allowed in the B4X static resolver section")
		}
	}
	return nil
}

// SortedKeys exposes the allowlist for tests/documentation.
func SortedKeys() []string {
	out := make([]string, 0, len(allowedKeys))
	for k := range allowedKeys {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}
