#!/usr/bin/env python3
"""B4X FB-36: generate Go capability dependency graph from
specs/registries/capability_dependencies.yaml.

Emits `src/validation/capability_deps.gen.go` (package validation):
- `CapabilityDependency` — canonical capability record (execution scheduling);
- `capabilityDependencies` — full canonical capability list (data only);
- accessors: `Capabilities()`, `CapabilityByID()`.

The generated file is the ONLY runtime reference to the registry data
(owner decision pattern from FB-33, applied to FB-34/FB-31 and FB-36).
Logic (execution order, closure, upstream guard, validation) lives in
src/validation/capability_deps.go — never edit the generated file.

Usage: python tools/gen_capability_deps_go.py [--check]
"""

from __future__ import annotations

import sys
from pathlib import Path

try:
    import yaml
except ImportError:  # pragma: no cover
    sys.exit("PyYAML is required: pip install pyyaml")

REPO = Path(__file__).resolve().parent.parent
REGISTRY = REPO / "specs" / "registries" / "capability_dependencies.yaml"
OUT = REPO / "src" / "validation" / "capability_deps.gen.go"

HEADER = """// Code generated by tools/gen_capability_deps_go.py from
// specs/registries/capability_dependencies.yaml. DO NOT EDIT.
//
// Canonical Capability Dependency Graph (FB-36, b4x-0yf). Single source of
// truth: specs/registries/capability_dependencies.yaml. Encodes the
// normative execution schedule (B4X_AUDIT_FIX_TASKS v2 §FB-36): parallel
// physical execution where safe, strict dependency aggregation (missing
// upstream dependency blocks downstream PASS).
package validation

"""


def go_string(v) -> str:
    if v is None:
        return '""'
    return f'"{str(v)}"'


def go_str_slice(items) -> str:
    if not items:
        return "nil"
    return "[]string{" + ", ".join(go_string(s) for s in items) + "}"


def render(data) -> str:
    lines: list[str] = [HEADER]

    declared = data.get("declared_total")
    lines.append("// CapabilityDeclaredTotal is the declared registry total")
    lines.append("// (generator enforces declared_total == computed_total == count(capabilities)).")
    lines.append(f"const CapabilityDeclaredTotal = {declared}\n")

    lines.append("// CapabilityDependency is one canonical capability stage of the")
    lines.append("// FB-36 execution scheduling graph.")
    lines.append("type CapabilityDependency struct {")
    lines.append("\tID       string   // canonical capability id")
    lines.append("\tName     string   // normative stage name")
    lines.append("\tLayer    int      // monotone graph depth; parallel wave grouping")
    lines.append("\tRequires []string // upstream capabilities (dependencies first)")
    lines.append("\tParallel bool     // may run in parallel (not in the strict chain)")
    lines.append("\tOptional bool     // activated only when selected (base WARP readiness)")
    lines.append("}\n")

    lines.append("// capabilityDependencies holds the full canonical capability list (auto-generated).")
    lines.append("var capabilityDependencies = []CapabilityDependency{")
    for c in data["capabilities"]:
        lines.append("\t{")
        lines.append(f"\t\tID:       {go_string(c['id'])}, ")
        lines.append(f"\t\tName:     {go_string(c.get('name'))}, ")
        lines.append(f"\t\tLayer:    {int(c.get('layer', 0))}, ")
        lines.append(f"\t\tRequires: {go_str_slice(c.get('requires'))}, ")
        lines.append(f"\t\tParallel: {str(bool(c.get('parallel', False))).lower()}, ")
        lines.append(f"\t\tOptional: {str(bool(c.get('optional', False))).lower()}, ")
        lines.append("\t},")
    lines.append("}\n")

    lines.append("// Capabilities returns the full canonical capability dependency registry.")
    lines.append("func Capabilities() []CapabilityDependency { return capabilityDependencies }\n")

    lines.append("// CapabilityByID returns the capability with the given canonical id.")
    lines.append("func CapabilityByID(id string) (CapabilityDependency, bool) {")
    lines.append("\tfor _, c := range capabilityDependencies {")
    lines.append("\t\tif c.ID == id {")
    lines.append("\t\t\treturn c, true")
    lines.append("\t\t}")
    lines.append("\t}")
    lines.append("\treturn CapabilityDependency{}, false")
    lines.append("}\n")

    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    import argparse
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="verify committed generated file is current; exit non-zero on mismatch")
    args = ap.parse_args(argv)

    with REGISTRY.open(encoding="utf-8") as fh:
        data = yaml.safe_load(fh)

    text = render(data)
    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            print(f"STALE {OUT}: generated Go registry does not match "
                  f"specs/registries/capability_dependencies.yaml; "
                  f"run `python tools/gen_capability_deps_go.py` and commit the result.")
            return 1
        print(f"OK {OUT}: generated Go registry is current "
              f"({len(data['capabilities'])} capabilities)")
        return 0

    OUT.write_text(text, encoding="utf-8", newline="\n")
    try:
        import shutil
        import subprocess
        if shutil.which("gofmt"):
            subprocess.run(["gofmt", "-w", str(OUT)], check=True)
    except Exception:  # pragma: no cover
        pass
    print(f"WROTE {OUT}: {len(data['capabilities'])} capabilities")
    return 0


if __name__ == "__main__":
    sys.exit(main())
