#!/usr/bin/env python3
"""B4X FB-33: generate Go registry references from specs/registries/source_stage_registry.yaml.

Emits `src/validation/source_stage_registry.gen.go` (package validation):
- `SourceStageRequirement` — normative schema record (FB-33);
- `sourceStageRequirements` — full canonical requirement list;
- `sourceStageDocuments` — normative documents (name/version/category/sha256);
- accessors: `SourceStageRequirements()`, `SourceStageRequirementByID()`,
  `SourceStageDocuments()`, `SourceStageDocumentHash()`.

The generated file is the ONLY runtime reference to the registry
(owner decision 2026-08-01 pattern, applied to FB-33 on 2026-08-05).

Usage: python tools/gen_source_stage_go.py
"""

from __future__ import annotations

import sys
from pathlib import Path

try:
    import yaml
except ImportError:  # pragma: no cover
    sys.exit("PyYAML is required: pip install pyyaml")

REPO = Path(__file__).resolve().parent.parent
REGISTRY = REPO / "specs" / "registries" / "source_stage_registry.yaml"
OUT = REPO / "src" / "validation" / "source_stage_registry.gen.go"

HEADER = """// Code generated by tools/gen_source_stage_go.py from
// specs/registries/source_stage_registry.yaml. DO NOT EDIT.
//
// Canonical Exact Source-Stage Registry (FB-33, b4x-yzt). Single source of
// truth: specs/registries/source_stage_registry.yaml (FB-14 решения 6/7;
// criteria_total = count(valid canonical registry entries)).
package validation

"""


def go_string(v) -> str:
    if v is None:
        return '""'
    return f'"{str(v)}"'


def go_str_slice(items) -> str:
    if not items:
        return "nil"
    return "[]string{" + ", ".join(go_string(s) for s in items) + "}"


def main() -> int:
    with REGISTRY.open(encoding="utf-8") as fh:
        data = yaml.safe_load(fh)

    lines: list[str] = [HEADER]

    lines.append("// SourceStageRequirement is one canonical source-stage registry entry.")
    lines.append("// Schema (B4X_AUDIT_FIX_TASKS v2 §FB-33): RequirementID, SourceDocument,")
    lines.append("// SourceVersion, SourceSHA256, Section, Stage, Category, Dependencies,")
    lines.append("// Suites, Gates, Verdicts, Applicability.")
    lines.append("type SourceStageRequirement struct {")
    lines.append('\tRequirementID  string   // canonical requirement identifier (e.g. CSI-1, ABD-12)')
    lines.append('\tSourceDocument string   // normative document file name')
    lines.append('\tSourceVersion  string   // document version')
    lines.append('\tSourceSHA256   string   // SHA-256 of the normative document at generation time')
    lines.append('\tSection        string   // normative section (e.g. 41.1, 84-92)')
    lines.append('\tStage          string   // stage the requirement is enforced at')
    lines.append('\tCategory       string   // category (architecture|patch-plan|implementation|companion|source-stage|...)')
    lines.append('\tDependencies   []string // §54 companion coverage dependencies (requirement IDs)')
    lines.append('\tSuites         []string // umbrella suites (IV-6/8/12/14/15/16/17)')
    lines.append('\tGates          []string // hard gates (populated by FB-03/34 wiring)')
    lines.append('\tVerdicts       []string // principal verdict families (FB-34 will attach aliases)')
    lines.append('\tApplicability  string   // applicable scope (family:... | all)')
    lines.append("}\n")

    lines.append("// SourceStageDocument describes one normative document in the registry.")
    lines.append("type SourceStageDocument struct {")
    lines.append('\tName     string')
    lines.append('\tVersion  string')
    lines.append('\tCategory string')
    lines.append('\tSHA256   string')
    lines.append("}\n")

    declared = data.get("declared_total")
    lines.append(f"// SourceStageDeclaredTotal is the declared criteria total (computed by the")
    lines.append(f"// generator: declared_total == computed_total == count(valid entries)).")
    lines.append(f"const SourceStageDeclaredTotal = {declared}\n")

    lines.append("// sourceStageRequirements holds the full canonical registry (auto-generated).")
    lines.append("var sourceStageRequirements = []SourceStageRequirement{")
    for r in data["requirements"]:
        lines.append("\t{")
        lines.append(f"\t\tRequirementID:  {go_string(r['requirement_id'])}, ")
        lines.append(f"\t\tSourceDocument: {go_string(r['source_document'])}, ")
        lines.append(f"\t\tSourceVersion:  {go_string(r['source_version'])}, ")
        lines.append(f"\t\tSourceSHA256:   {go_string(r['source_sha256'])}, ")
        lines.append(f"\t\tSection:        {go_string(r['section'])}, ")
        lines.append(f"\t\tStage:          {go_string(r['stage'])}, ")
        lines.append(f"\t\tCategory:       {go_string(r['category'])}, ")
        lines.append(f"\t\tDependencies:   {go_str_slice(r.get('dependencies'))}, ")
        lines.append(f"\t\tSuites:         {go_str_slice(r.get('suites'))}, ")
        lines.append(f"\t\tGates:          {go_str_slice(r.get('gates'))}, ")
        lines.append(f"\t\tVerdicts:       {go_str_slice(r.get('verdicts'))}, ")
        lines.append(f"\t\tApplicability:  {go_string(r.get('applicability'))}, ")
        lines.append("\t},")
    lines.append("}\n")

    lines.append("// sourceStageDocuments holds the normative documents (auto-generated).")
    lines.append("var sourceStageDocuments = []SourceStageDocument{")
    for d in data["documents"]:
        lines.append("\t{")
        lines.append(f"\t\tName: {go_string(d['name'])}, Version: {go_string(d['version'])}, ")
        lines.append(f"\t\tCategory: {go_string(d['category'])}, SHA256: {go_string(d['sha256'])}, ")
        lines.append("\t},")
    lines.append("}\n")

    lines.append("// SourceStageRequirements returns the full canonical requirement registry.")
    lines.append("func SourceStageRequirements() []SourceStageRequirement { return sourceStageRequirements }\n")

    lines.append("// SourceStageRequirementByID returns the requirement with the given ID.")
    lines.append("func SourceStageRequirementByID(id string) (SourceStageRequirement, bool) {")
    lines.append("\tfor _, r := range sourceStageRequirements {")
    lines.append("\t\tif r.RequirementID == id {")
    lines.append("\t\t\treturn r, true")
    lines.append("\t\t}")
    lines.append("\t}")
    lines.append("\treturn SourceStageRequirement{}, false")
    lines.append("}\n")

    lines.append("// SourceStageDocuments returns the normative documents referenced by the registry.")
    lines.append("func SourceStageDocuments() []SourceStageDocument { return sourceStageDocuments }\n")

    lines.append("// SourceStageDocumentHash returns the recorded SHA-256 of a normative document.")
    lines.append("func SourceStageDocumentHash(name string) (string, bool) {")
    lines.append("\tfor _, d := range sourceStageDocuments {")
    lines.append("\t\tif d.Name == name {")
    lines.append("\t\t\treturn d.SHA256, true")
    lines.append("\t\t}")
    lines.append("\t}")
    lines.append("\treturn \"\", false")
    lines.append("}\n")

    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    # Best-effort gofmt (CI/Linux); on hosts without Go the generated file is
    # still valid Go, just not column-aligned (run gofmt -w manually if needed).
    try:
        import shutil
        import subprocess
        if shutil.which("gofmt"):
            subprocess.run(["gofmt", "-w", str(OUT)], check=True)
    except Exception:  # pragma: no cover
        pass
    print(f"WROTE {OUT}: {len(data['requirements'])} requirements, {len(data['documents'])} documents")
    return 0


if __name__ == "__main__":
    sys.exit(main())
