#!/usr/bin/env python3
"""B4X FB-31: generate Go registry data from specs/registries/causal_eligibility_matrix.yaml.

Emits `src/validation/causal_eligibility.gen.go` (package validation):
- `CandidateFamily` — candidate family catalog entry;
- `CausalEligibility` — failure family -> candidate family mapping (FB-31);
- `candidateFamilies` / `causalEligibilities` — data (generated only);
- accessors: `CandidateFamilies()`, `CausalEligibilities()`,
  `CausalEligibilityByFamily()`.

The generated file is the ONLY runtime reference to the registry data
(owner decision pattern from FB-33/FB-34). Logic (transport authorization,
hypothesis mapping, guards) lives in src/validation/causal_eligibility.go —
never edit the generated file.

Usage: python tools/gen_causal_matrix_go.py [--check]

  (no flag)   regenerate src/validation/causal_eligibility.gen.go
  --check     verify the committed generated file matches the current
              registry; exit non-zero on mismatch (stale .gen.go detected,
              FB-31 CI gate).
"""

from __future__ import annotations

import sys
from pathlib import Path

try:
    import yaml
except ImportError:  # pragma: no cover
    sys.exit("PyYAML is required: pip install pyyaml")

REPO = Path(__file__).resolve().parent.parent
REGISTRY = REPO / "specs" / "registries" / "causal_eligibility_matrix.yaml"
OUT = REPO / "src" / "validation" / "causal_eligibility.gen.go"

HEADER = """// Code generated by tools/gen_causal_matrix_go.py from
// specs/registries/causal_eligibility_matrix.yaml. DO NOT EDIT.
//
// Causal eligibility matrix (FB-31, b4x-cka). Single source of truth:
// specs/registries/causal_eligibility_matrix.yaml. Maps every failure
// family to eligible/forbidden candidate families, mandatory narrower
// families, prerequisites, controls, target validation and scoped transport
// authorization rules.
package validation

"""


def go_string(v) -> str:
    if v is None:
        return '""'
    return f'"{str(v)}"'


def go_str_slice(items) -> str:
    if not items:
        return "nil"
    return "[]string{" + ", ".join(go_string(s) for s in items) + "}"


def render(data) -> str:
    lines: list[str] = [HEADER]

    lines.append("// CandidateFamilyKind is the catalog role of a candidate family.")
    lines.append("type CandidateFamilyKind string")
    lines.append("")
    lines.append("const (")
    lines.append('\tCandidateKindEligible  CandidateFamilyKind = "eligible"')
    lines.append('\tCandidateKindShadow    CandidateFamilyKind = "shadow"')
    lines.append('\tCandidateKindForbidden CandidateFamilyKind = "forbidden"')
    lines.append(")\n")

    lines.append("// CandidateFamily is one candidate family in the FB-31 catalog.")
    lines.append("type CandidateFamily struct {")
    lines.append("\tFamily    string")
    lines.append("\tKind      CandidateFamilyKind")
    lines.append("\tTransport bool")
    lines.append("\tNote      string")
    lines.append("}\n")

    lines.append("// candidateFamilies holds the candidate family catalog (auto-generated).")
    lines.append("var candidateFamilies = []CandidateFamily{")
    for c in data["candidate_families"]:
        lines.append("\t{")
        lines.append(f"\t\tFamily:    {go_string(c.get('family'))}, ")
        lines.append(f"\t\tKind:      CandidateFamilyKind({go_string(c.get('kind'))}), ")
        lines.append(f"\t\tTransport: {'true' if c.get('transport') else 'false'}, ")
        lines.append(f"\t\tNote:      {go_string(c.get('note'))}, ")
        lines.append("\t},")
    lines.append("}\n")

    lines.append("// CausalEligibility is the FB-31 mapping of one failure family.")
    lines.append("type CausalEligibility struct {")
    lines.append("\tFamily                  string")
    lines.append("\tTitle                   string")
    lines.append("\tSourceDoc               string")
    lines.append("\tSourceSection           string")
    lines.append("\tHypotheses              []string")
    lines.append("\tEligibleCandidateFamilies  []string")
    lines.append("\tForbiddenCandidateFamilies []string")
    lines.append("\tMandatoryNarrowerFamilies  []string")
    lines.append("\tShadowCandidateFamilies    []string")
    lines.append("\tPrerequisites           []string")
    lines.append("\tControls                []string")
    lines.append("\tTargetValidation        []string")
    lines.append("\tTransportAuthorization  string")
    lines.append("\tRequiredEvidenceAuthority string")
    lines.append("}\n")

    declared = data.get("declared_total")
    lines.append("// CausalEligibilityDeclaredTotal is the declared registry total")
    lines.append("// (generator enforces declared_total == computed_total == count(valid entries)).")
    lines.append(f"const CausalEligibilityDeclaredTotal = {declared}\n")

    lines.append("// causalEligibilities holds the full failure family matrix (auto-generated).")
    lines.append("var causalEligibilities = []CausalEligibility{")
    for f in data["failure_families"]:
        lines.append("\t{")
        lines.append(f"\t\tFamily:                  {go_string(f.get('family'))}, ")
        lines.append(f"\t\tTitle:                   {go_string(f.get('title'))}, ")
        lines.append(f"\t\tSourceDoc:               {go_string(f.get('source_doc'))}, ")
        lines.append(f"\t\tSourceSection:           {go_string(f.get('source_section'))}, ")
        lines.append(f"\t\tHypotheses:              {go_str_slice(f.get('hypotheses'))}, ")
        lines.append(f"\t\tEligibleCandidateFamilies:  {go_str_slice(f.get('eligible_candidate_families'))}, ")
        lines.append(f"\t\tForbiddenCandidateFamilies: {go_str_slice(f.get('forbidden_candidate_families'))}, ")
        lines.append(f"\t\tMandatoryNarrowerFamilies:  {go_str_slice(f.get('mandatory_narrower_families'))}, ")
        lines.append(f"\t\tShadowCandidateFamilies:    {go_str_slice(f.get('shadow_candidate_families'))}, ")
        lines.append(f"\t\tPrerequisites:           {go_str_slice(f.get('prerequisites'))}, ")
        lines.append(f"\t\tControls:                {go_str_slice(f.get('controls'))}, ")
        lines.append(f"\t\tTargetValidation:        {go_str_slice(f.get('target_validation'))}, ")
        lines.append(f"\t\tTransportAuthorization:  {go_string(f.get('transport_authorization'))}, ")
        lines.append(f"\t\tRequiredEvidenceAuthority: {go_string(f.get('required_evidence_authority'))}, ")
        lines.append("\t},")
    lines.append("}\n")

    lines.append("// CandidateFamilies returns the candidate family catalog.")
    lines.append("func CandidateFamilies() []CandidateFamily { return candidateFamilies }\n")

    lines.append("// CausalEligibilities returns the full failure family matrix.")
    lines.append("func CausalEligibilities() []CausalEligibility { return causalEligibilities }\n")

    lines.append("// CausalEligibilityByFamily returns the mapping for one failure family.")
    lines.append("func CausalEligibilityByFamily(family string) (CausalEligibility, bool) {")
    lines.append("\tfor _, e := range causalEligibilities {")
    lines.append("\t\tif e.Family == family {")
    lines.append("\t\t\treturn e, true")
    lines.append("\t\t}")
    lines.append("\t}")
    lines.append("\treturn CausalEligibility{}, false")
    lines.append("}\n")

    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    import argparse
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="verify committed generated file is current; exit non-zero on mismatch")
    args = ap.parse_args(argv)

    with REGISTRY.open(encoding="utf-8") as fh:
        data = yaml.safe_load(fh)

    text = render(data)
    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            print(f"STALE {OUT}: generated Go registry does not match "
                  f"specs/registries/causal_eligibility_matrix.yaml; "
                  f"run `python tools/gen_causal_matrix_go.py` and commit the result.")
            return 1
        print(f"OK {OUT}: generated Go registry is current "
              f"({len(data['failure_families'])} failure families, "
              f"{len(data['candidate_families'])} candidate families)")
        return 0

    OUT.write_text(text, encoding="utf-8", newline="\n")
    try:
        import shutil
        import subprocess
        if shutil.which("gofmt"):
            subprocess.run(["gofmt", "-w", str(OUT)], check=True)
    except Exception:  # pragma: no cover
        pass
    print(f"WROTE {OUT}: {len(data['failure_families'])} failure families, "
          f"{len(data['candidate_families'])} candidate families")
    return 0


if __name__ == "__main__":
    sys.exit(main())
