#!/usr/bin/env python3
"""B4X FB-03: generate Go registry references from specs/registries/hard_gates.yaml.

Emits `src/validation/hard_gates_registry.gen.go` (package validation):
- `Gate` metadata struct (registry schema per B4X_AUDIT_FIX_TASKS v2 §0.6.2);
- `HardGates()` — full canonical gate list;
- `ApplicableHardGates()` — gates with a runtime producer;
- `HardGateByName(name)` — lookup.

The generated file is the ONLY runtime reference to the registry
(owner decision 2026-08-01: runtime code = generated references).

Usage: python tools/gen_hard_gates_go.py
"""

from __future__ import annotations

import sys
from pathlib import Path

try:
    import yaml
except ImportError:  # pragma: no cover
    sys.exit("PyYAML is required: pip install pyyaml")

REPO = Path(__file__).resolve().parent.parent
REGISTRY = REPO / "specs" / "registries" / "hard_gates.yaml"
OUT = REPO / "src" / "validation" / "hard_gates_registry.gen.go"

HEADER = """// Code generated by tools/gen_hard_gates_go.py from
// specs/registries/hard_gates.yaml. DO NOT EDIT.
//
// Canonical hard-gate registry (FB-03). Single source of truth:
// specs/registries/hard_gates.yaml (owner decision 2026-08-01).
package validation

"""


def go_string(v) -> str:
    if v is None:
        return '""'
    return f'"{str(v)}"'


def go_bool(v) -> str:
    return "true" if v else "false"


def go_line(v) -> str:
    """Render a YAML int-or-null line reference as a Go int."""
    if v is None:
        return "0"
    return str(int(v))


def go_producer_ref(p) -> str:
    """Render a runtime_producer descriptor (dict) as a ProducerRef literal."""
    if not p:
        return "ProducerRef{}"
    return (
        f"ProducerRef{{Symbol: {go_string(p.get('symbol'))}, "
        f"File: {go_string(p.get('file'))}, Line: {go_line(p.get('line'))}, "
        f"Mechanism: {go_string(p.get('mechanism'))}, "
        f"ProductionRoot: {go_string(p.get('production_root'))}}}"
    )


def go_consumer_refs(items) -> str:
    if not items:
        return "nil"
    parts = [(
        f"ConsumerRef{{Kind: {go_string(c.get('kind'))}, "
        f"Symbol: {go_string(c.get('symbol'))}, File: {go_string(c.get('file'))}, "
        f"Line: {go_line(c.get('line'))}, Binding: {go_string(c.get('binding'))}}}"
    ) for c in items]
    return "[]ConsumerRef{" + ", ".join(parts) + "}"


def go_test_refs(items, ref_type: str) -> str:
    if not items:
        return "nil"
    parts = []
    for t in items:
        if ref_type == "TestRef":
            parts.append(
                f"TestRef{{Kind: {go_string(t.get('kind'))}, Name: {go_string(t.get('name'))}, "
                f"File: {go_string(t.get('file'))}, Line: {go_line(t.get('line'))}, "
                f"Assertion: {go_string(t.get('assertion'))}}}"
            )
        else:
            parts.append(
                f"MutationRef{{Kind: {go_string(t.get('kind'))}, Name: {go_string(t.get('name'))}, "
                f"File: {go_string(t.get('file'))}, Status: {go_string(t.get('status'))}}}"
            )
    return f"[]{ref_type}{{" + ", ".join(parts) + "}"


def go_str_slice(items) -> str:
    if not items:
        return "nil"
    return "[]string{" + ", ".join(go_string(s) for s in items) + "}"


def main() -> int:
    with REGISTRY.open(encoding="utf-8") as fh:
        data = yaml.safe_load(fh)

    lines: list[str] = [HEADER]
    lines.append("// GateKind classifies what a registry entry actually is.")
    lines.append("// Only zero_tolerance_violation_counter gates may block promotion;")
    lines.append("// telemetry_counter entries are operational counters, not gates.")
    lines.append("const (")
    lines.append('\tGateKindTelemetry  = "telemetry_counter"')
    lines.append('\tGateKindZeroTol    = "zero_tolerance_violation_counter"')
    lines.append(")\n")

    lines.append("// ProducerRef is a machine-readable verified producer descriptor.")
    lines.append("type ProducerRef struct {")
    lines.append("\tSymbol        string `json:\"symbol\"`")
    lines.append("\tFile          string `json:\"file\"`")
    lines.append("\tLine          int    `json:\"line\"`")
    lines.append("\tMechanism     string `json:\"mechanism\"`")
    lines.append("\tProductionRoot string `json:\"production_root\"`")
    lines.append("}\n")

    lines.append("// ConsumerRef is a machine-readable verdict consumer descriptor.")
    lines.append("// Kind: promotion_blocker | aggregation_blocker | http_report.")
    lines.append("type ConsumerRef struct {")
    lines.append("\tKind    string `json:\"kind\"`")
    lines.append("\tSymbol  string `json:\"symbol\"`")
    lines.append("\tFile    string `json:\"file\"`")
    lines.append("\tLine    int    `json:\"line\"`")
    lines.append("\tBinding string `json:\"binding\"`")
    lines.append("}\n")

    lines.append("// TestRef is a machine-readable test fixture exercising a producer.")
    lines.append("// Kind: positive_fixture | negative_fixture | evaluator_fixture.")
    lines.append("type TestRef struct {")
    lines.append("\tKind      string `json:\"kind\"`")
    lines.append("\tName      string `json:\"name\"`")
    lines.append("\tFile      string `json:\"file\"`")
    lines.append("\tLine      int    `json:\"line\"`")
    lines.append("\tAssertion string `json:\"assertion\"`")
    lines.append("}\n")

    lines.append("// MutationRef records an executed mutation test (producer removed).")
    lines.append("type MutationRef struct {")
    lines.append("\tKind   string `json:\"kind\"`")
    lines.append("\tName   string `json:\"name\"`")
    lines.append("\tFile   string `json:\"file\"`")
    lines.append("\tStatus string `json:\"status\"`")
    lines.append("}\n")

    lines.append("// Gate describes one canonical hard gate (registry schema v1.1).")
    lines.append("type Gate struct {")
    lines.append("\tGateID               string // canonical gate identifier (metric name)")
    lines.append("\tGlobalGateClass      string // class from owner addendum section")
    lines.append("\tOwnerFamily          string // canonical owner family")
    lines.append("\tOwnerStage           string // stage the gate is enforced at")
    lines.append("\tSourceDoc            string // owner addendum file")
    lines.append("\tSourceSection        string // owner addendum section")
    lines.append("\tKind                 string // telemetry_counter | zero_tolerance_violation_counter")
    lines.append("\tProducerStatus       string // verified | missing")
    lines.append("\tRuntimeProducer      ProducerRef // verified producer (zero value = not verified)")
    lines.append("\tExpectedProducerLocation string // owner-normative file where producer must live")
    lines.append("\tVerdictConsumers     []ConsumerRef // machine-readable consumer chain")
    lines.append("\tTestProducers        []TestRef     // fixtures exercising the producer")
    lines.append("\tMutationTests        []MutationRef // executed mutation tests")
    lines.append("\tEvidenceArtifacts    []string      // backing audit/remediation artifacts")
    lines.append("\tPromotionBlocker     bool   // blocks promotion when non-zero (only zero-tolerance)")
    lines.append("\tResetSemantics       string // increment-only; verified == 0 | telemetry")
    lines.append("\tApplicability        string // applicable scope (family:...)")
    lines.append("}\n")

    lines.append("// hardGates holds the full canonical registry (auto-generated).")
    lines.append("var hardGates = []Gate{")
    total = 0
    for fam, gates in data["families"].items():
        for g in gates:
            total += 1
            lines.append("\t{")
            lines.append(f"\t\tGateID:          {go_string(g['gate_id'])}, // {fam}")
            lines.append(f"\t\tGlobalGateClass: {go_string(g['global_gate_class'])}, ")
            lines.append(f"\t\tOwnerFamily:     {go_string(g['owner_family'])}, ")
            lines.append(f"\t\tOwnerStage:      {go_string(g['owner_stage'])}, ")
            lines.append(f"\t\tSourceDoc:       {go_string(g['source_doc'])}, ")
            lines.append(f"\t\tSourceSection:   {go_string(g['source_section'])}, ")
            lines.append(f"\t\tKind:            {go_string(g.get('kind', 'zero_tolerance_violation_counter'))}, ")
            lines.append(f"\t\tProducerStatus:  {go_string(g.get('producer_status', 'missing'))}, ")
            lines.append(f"\t\tRuntimeProducer: {go_producer_ref(g.get('runtime_producer'))}, ")
            lines.append(f"\t\tExpectedProducerLocation: {go_string(g.get('expected_producer_location'))}, ")
            lines.append(f"\t\tVerdictConsumers: {go_consumer_refs(g.get('verdict_consumer'))}, ")
            lines.append(f"\t\tTestProducers:   {go_test_refs(g.get('test_producer'), 'TestRef')}, ")
            lines.append(f"\t\tMutationTests:   {go_test_refs(g.get('mutation_test'), 'MutationRef')}, ")
            lines.append(f"\t\tEvidenceArtifacts: {go_str_slice(g.get('evidence_artifact'))}, ")
            lines.append(f"\t\tPromotionBlocker: {go_bool(g.get('promotion_blocker', True))}, ")
            lines.append(f"\t\tResetSemantics:  {go_string(g.get('reset_semantics'))}, ")
            lines.append(f"\t\tApplicability:   {go_string(g.get('applicability'))}, ")
            lines.append("\t},")
    lines.append("}\n")

    lines.append("// HardGates returns the full canonical registry.")
    lines.append("func HardGates() []Gate { return hardGates }\n")

    lines.append("// ApplicableHardGates returns gates with a verified runtime producer")
    lines.append("// (applicable subset; gates without producer cannot PASS per v2 §0.6.3).")
    lines.append("func ApplicableHardGates() []Gate {")
    lines.append("\tvar out []Gate")
    lines.append("\tfor _, g := range hardGates {")
    lines.append("\t\tif g.ProducerStatus == \"verified\" {")
    lines.append("\t\t\tout = append(out, g)")
    lines.append("\t\t}")
    lines.append("\t}")
    lines.append("\treturn out")
    lines.append("}\n")

    lines.append("// HardGateByName returns the gate with the given canonical metric name.")
    lines.append("func HardGateByName(name string) (Gate, bool) {")
    lines.append("\tfor _, g := range hardGates {")
    lines.append("\t\tif g.GateID == name {")
    lines.append("\t\t\treturn g, true")
    lines.append("\t\t}")
    lines.append("\t}")
    lines.append("\treturn Gate{}, false")
    lines.append("}\n")

    lines.append("// HardGateCount returns the number of gates in the canonical registry.")
    lines.append("func HardGateCount() int { return len(hardGates) }\n")

    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    # Best-effort gofmt (CI/Linux); on hosts without Go the generated file is
    # still valid Go, just not column-aligned (run gofmt -w manually if needed).
    try:
        import shutil
        import subprocess
        if shutil.which("gofmt"):
            subprocess.run(["gofmt", "-w", str(OUT)], check=True)
    except Exception:  # pragma: no cover
        pass
    applicable = sum(1 for fam, gates in data["families"].items()
                     for g in gates if g.get("runtime_producer"))
    print(f"WROTE {OUT}: {total} gates, {applicable} applicable (with producer)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
