#!/usr/bin/env python3
"""B4X FB-34: generate Go registry data from specs/registries/principal_verdicts.yaml.

Emits `src/validation/principal_verdicts.gen.go` (package validation):
- `PrincipalVerdict` — canonical principal verdict record (FB-34);
- `principalVerdicts` — full canonical verdict list (data only);
- accessors: `PrincipalVerdicts()`, `PrincipalVerdictByCanonical()`.

The generated file is the ONLY runtime reference to the registry data
(owner decision pattern from FB-33, applied to FB-34 on 2026-08-05).
Logic (alias mapping, validation, dependency closure) lives in
src/validation/principal_verdicts.go — never edit the generated file.

Usage: python tools/gen_principal_verdicts_go.py
"""

from __future__ import annotations

import sys
from pathlib import Path

try:
    import yaml
except ImportError:  # pragma: no cover
    sys.exit("PyYAML is required: pip install pyyaml")

REPO = Path(__file__).resolve().parent.parent
REGISTRY = REPO / "specs" / "registries" / "principal_verdicts.yaml"
OUT = REPO / "src" / "validation" / "principal_verdicts.gen.go"

HEADER = """// Code generated by tools/gen_principal_verdicts_go.py from
// specs/registries/principal_verdicts.yaml. DO NOT EDIT.
//
// Canonical Principal Verdict Registry (FB-34, b4x-xgc). Single source of
// truth: specs/registries/principal_verdicts.yaml. Unifies ARCH §142,
// IV §52/§52.1, §83 and §88 verdict names with alias mapping.
package validation

"""


def go_string(v) -> str:
    if v is None:
        return '""'
    return f'"{str(v)}"'


def go_str_slice(items) -> str:
    if not items:
        return "nil"
    return "[]string{" + ", ".join(go_string(s) for s in items) + "}"


def main() -> int:
    with REGISTRY.open(encoding="utf-8") as fh:
        data = yaml.safe_load(fh)

    lines: list[str] = [HEADER]

    lines.append("// PrincipalVerdict is one canonical principal verdict registry entry.")
    lines.append("// Schema (B4X_AUDIT_FIX_TASKS v2 §FB-34): canonical name, aliases,")
    lines.append("// owner stage, dependency expression, required gates, required target")
    lines.append("// evidence, blocked variants, expiry/invalidation rules.")
    lines.append("type PrincipalVerdict struct {")
    lines.append('\tCanonical            string   // canonical verdict name (runtime/API/UI/reports)')
    lines.append('\tAliases              []string // compatibility names only; no separate state store')
    lines.append('\tKind                 string   // ready | blocked (blocked != PASS_WITH_LIMITATIONS)')
    lines.append('\tOwnerFamily          string   // verdict family (abd|csi|ddi_tgb|mon|ppe|rst_gso|sp|spf|warp|adns|fieldtest)')
    lines.append('\tSourceStageCategory  string   // category in source_stage_registry.yaml, if any')
    lines.append('\tSourceDoc            string   // normative document file name')
    lines.append('\tSourceSection        string   // normative section (142, 52, 52.1, 83, 88)')
    lines.append('\tDependencies         []string // canonical names; aggregation follows the ARCH graph')
    lines.append('\tDependencyExpression string   // human-readable dependency rule from the source')
    lines.append('\tRequiredGates        []string // gate references (family:<name> form)')
    lines.append('\tRequiredTargetEvidence []string // target evidence kinds (dns|tls_http|quic|l4)')
    lines.append('\tBlockedVariants      []string // blocked verdicts that may substitute this one')
    lines.append('\tExpiry               []string // invalidation rules (config/evidence-generation-bound)')
    lines.append("}\n")

    declared = data.get("declared_total")
    lines.append("// PrincipalVerdictDeclaredTotal is the declared registry total")
    lines.append("// (generator enforces declared_total == computed_total == count(valid entries)).")
    lines.append(f"const PrincipalVerdictDeclaredTotal = {declared}\n")

    lines.append("// principalVerdicts holds the full canonical verdict registry (auto-generated).")
    lines.append("var principalVerdicts = []PrincipalVerdict{")
    for v in data["verdicts"]:
        lines.append("\t{")
        lines.append(f"\t\tCanonical:            {go_string(v['canonical'])}, ")
        lines.append(f"\t\tAliases:              {go_str_slice(v.get('aliases'))}, ")
        lines.append(f"\t\tKind:                 {go_string(v.get('kind'))}, ")
        lines.append(f"\t\tOwnerFamily:          {go_string(v.get('owner_family'))}, ")
        lines.append(f"\t\tSourceStageCategory:  {go_string(v.get('source_stage_category'))}, ")
        lines.append(f"\t\tSourceDoc:            {go_string(v.get('source_doc'))}, ")
        lines.append(f"\t\tSourceSection:        {go_string(v.get('source_section'))}, ")
        lines.append(f"\t\tDependencies:         {go_str_slice(v.get('dependencies'))}, ")
        lines.append(f"\t\tDependencyExpression: {go_string(v.get('dependency_expression'))}, ")
        lines.append(f"\t\tRequiredGates:        {go_str_slice(v.get('required_gates'))}, ")
        lines.append(f"\t\tRequiredTargetEvidence: {go_str_slice(v.get('required_target_evidence'))}, ")
        lines.append(f"\t\tBlockedVariants:      {go_str_slice(v.get('blocked_variants'))}, ")
        lines.append(f"\t\tExpiry:               {go_str_slice(v.get('expiry'))}, ")
        lines.append("\t},")
    lines.append("}\n")

    lines.append("// PrincipalVerdicts returns the full canonical principal verdict registry.")
    lines.append("func PrincipalVerdicts() []PrincipalVerdict { return principalVerdicts }\n")

    lines.append("// PrincipalVerdictByCanonical returns the verdict with the given canonical name.")
    lines.append("func PrincipalVerdictByCanonical(name string) (PrincipalVerdict, bool) {")
    lines.append("\tfor _, v := range principalVerdicts {")
    lines.append("\t\tif v.Canonical == name {")
    lines.append("\t\t\treturn v, true")
    lines.append("\t\t}")
    lines.append("\t}")
    lines.append("\treturn PrincipalVerdict{}, false")
    lines.append("}\n")

    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    try:
        import shutil
        import subprocess
        if shutil.which("gofmt"):
            subprocess.run(["gofmt", "-w", str(OUT)], check=True)
    except Exception:  # pragma: no cover
        pass
    print(f"WROTE {OUT}: {len(data['verdicts'])} verdicts")
    return 0


if __name__ == "__main__":
    sys.exit(main())
